LoadModule deflate_module modules/mod_deflate.so
LoadModule remoteip_module modules/mod_remoteip.so


AddOutputFilterByType DEFLATE \
application/xml \
text/html \
text/plain \
text/xml \
text/css \
text/javascript \
application/javascript \
application/vnd.cora.recordList+json \
application/vnd.cora.record+json \
application/vnd.cora.recordList+xml \
application/vnd.cora.record+xml \
application/xml \
application/vnd.cora.workorder+xml \
application/vnd.cora.workorder+json \
application/vnd.cora.record-decorated+xml \
application/vnd.cora.record-decorated+json \
application/vnd.cora.recordList-decorated+xml \
application/vnd.cora.recordList-decorated+json

RequestHeader set X-Original-URI expr=%{REQUEST_URI}

RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy 10.244.0.0/16

<Location "/server-status">
    SetHandler server-status
    Require ip 130.238.171.0/24 130.238.188.0/23 130.238.31.128/28 10.244.0.0/16
</Location>

#Below Best practices for apache running behind envoy gateway. 

## Use event MPM
#LoadModule mpm_event_module modules/mod_mpm_event.so
#
## Hide server version
#ServerTokens Prod
#ServerSignature Off
#
## Client IP from Envoy
#RemoteIPHeader X-Forwarded-For
#RemoteIPInternalProxy 10.0.0.0/8
#
## Timeouts
#Timeout 60
#KeepAlive On
#KeepAliveTimeout 3
#MaxKeepAliveRequests 100
#
## Security Headers
#Header always set X-Frame-Options "DENY"
#Header always set X-Content-Type-Options "nosniff"
#Header always set Referrer-Policy "strict-origin-when-cross-origin"
#Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
#
## Disable directory listing
#Options -Indexes
#
## Deny access to .ht* files
#<FilesMatch "^\.ht">
#    Require all denied
#</FilesMatch>
